spring:
  datasource:
    hikari:
      connection-timeout: 10000 # Default: 30_000 = 30 Sekunden
      idle-timeout: 120000 # Default: 600_000 = 10 Minuten
      maximum-pool-size: 3 # Default: 10
      minimum-idle: 1 # Default: maximumPoolSize

  flyway:
    # tablespace: paymentspace
    clean-disabled: false
    locations: classpath:db/migration/dev

  devtools:
    livereload:
      enabled: true
    restart:
      trigger-file: .reloadtrigger
  config:
    activate:
      on-profile: dev
  ssl:
    bundle:
      pem:
        microservice:
          reload-on-update: true
          keystore:
            private-key: "${app.keys.path}/key.pem"
            certificate: "${app.keys.path}/certificate.crt"
          truststore:
            certificate: "${app.keys.path}/certificate.crt"

# Applikationsspezifische Einstellungen
app:
  server:
    port: ${SERVER_PORT}
  postgres:
    url: jdbc:postgresql://${POSTGRES_SQL_HOST}:${POSTGRES_SQL_PORT}/${POSTGRES_SQL_DB}
    username: ${POSTGRES_SQL_USERNAME}
    password: ${POSTGRES_SQL_PASSWORD}
  keys:
    path: ${KEYS_PATH}

  http2:
    enabled: ${HTTPS:true}
  ssl:
    enabled: ${HTTPS:true}